name: Generate Static Drug Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [drugs-updated]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install fflate

      - name: Download drugs.json.gz from GitHub
        run: |
          curl -L "https://raw.githubusercontent.com/infopharmsoft-dotcom/Infopharm-Data1/main/drugs.json.gz" \
               -o drugs.json.gz

      - name: Download indications.json
        run: |
          curl -L "https://raw.githubusercontent.com/infopharmsoft-dotcom/Infopharm-Data1/refs/heads/main/indications.json" \
               -o indications.json

      - name: Generate static pages
        run: node generate.js

      - name: Generate Sitemap
        run: node sitemap.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
